# -------------------------------------
# Spencer Albrecht
# salbrech
# 12M
# Makefile for lab2
# -------------------------------------
Recursion: Recursion.class
	echo Main-class: Recursion > Manifest
	jar cvfm Recursion Manifest Recursion.class
	rm Manifest
	chmod +x Recursion
Recursion.class: Recursion.java
	javac Recursion.java
clean
	rm -f Recursion Recursion.class
